version: "3.9"
services:
  http-server:
    image: fadinglight/bill-http-server:v1.0.0-beta
    environment:
      - PORT=8080
      - MONGO_SERVER=mongo
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=123456
      - MONGO_DATABASE=bill
    ports:
      - "8081:8080"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /root/docker/volumes/bill-sys/mongo/:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456