DELETE http://localhost:8080/bill/2022-01-01/61f7cdb580430a1d62cbecd1
Accept: application/json

###
POST http://localhost:8080/bill/2022-01-01
Content-Type: application/json

{
  "money": "123",
  "labels": [
    "餐饮",
    "奶茶"
  ]
}

###
GET http://localhost:8080/bills
Accept: application/json

